services:
  nodejs:
    container_name: discord_bot
    build: .
    restart: always
    volumes:
      - ../:/app/discordBot
    command: >
      bash -c "cd /app/discordBot && npm install && npm run prod"
