FROM node:23
RUN apt-get update -y && apt-get upgrade -y && apt update -y && apt upgrade
RUN apt install ffmpeg -y
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/sbin/yt-dlp && chmod a+rx /usr/sbin/yt-dlp
